- name: prepare some dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: 101
    owner: 101
  with_items:
  - "{{ work_dir }}"
  - "{{ work_dir +'/conf.d' }}"
  - "{{ work_dir +'/data' }}"
  - "{{ work_dir +'/data/temp/client_temp' }}"
  - "{{ work_dir +'/data/temp/proxy_temp_path' }}"
  - "{{ work_dir +'/data/temp/fastcgi_temp' }}"
  - "{{ work_dir +'/data/temp/uwsgi_temp' }}"
  - "{{ work_dir +'/data/temp/scgi_temp' }}"
  when: install_type == "install"

- name: tar files
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{pkg_dir}}/{{item}}"
  with_items:
  - "nginx.tgz"
  when: install_type == "install"

- name: template start script
  template:
    dest: "{{work_dir}}/init.sh"
    src: "{{conf_dir}}/init.sh.j2"
  when: install_type == "install"

- name: htpasswd nginx config
  htpasswd:
    path: "{{conf_dir}}/pass.db"
    name: admin
    password: "{{ vmauth_pass }}"
    mode: 0644
    crypt_scheme: bcrypt
    group: 101
    owner: 101
  delegate_to: localhost
  run_once: true
  when: install_type == "install"

- name: template config yml
  template:
    dest: "{{work_dir}}/nginx.conf"
    src: "{{conf_dir}}/nginx.conf.j2"
  when: install_type == "install"

- name: template config yml
  template:
    dest: "{{work_dir}}/conf.d/monit.conf"
    src: "{{conf_dir}}/monit.conf.j2"
  when: install_type == "install"

- name: copy pass.db
  copy:
    dest: "{{work_dir}}/pass.db"
    src: "{{conf_dir}}/pass.db"
    group: 101
    owner: 101
    mode: 0644
  when: install_type == "install"

- name: "start"
  shell: "bash {{work_dir}}/init.sh"
  when: install_type == "install"

- name: stop all nginx
  shell: "docker rm -f {{service_name}}"
  ignore_errors: true
  when: install_type == "delete"

- name: clean all nginx data
  shell: "rm -rf {{ work_dir }}"
  ignore_errors: true
  when: install_type == "delete"
