- name: prepare some dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
  - "{{ work_dir }}"
  - "{{ work_dir +'/db'}}"
  - "{{ work_dir +'/conf'}}"
  - "{{ work_dir +'/logs'}}"
  when: install_type == "install"

- name: tar files
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{pkg_dir}}/{{item}}"
  with_items:
  - "promealert.tgz"
  when: install_type == "install"

- name: copy template files
  copy:
    dest: "{{work_dir}}/{{item}}"
    src: "{{conf_dir}}/{{item}}"
  with_items:
  - "prome-wx-custom.json"
  when: install_type == "install"

- name: template app.conf
  template:
    dest: "{{work_dir}}/conf/app.conf"
    src: "{{conf_dir}}/app.conf.j2"
  when: install_type == "install"


- name: template start script
  template:
    dest: "{{work_dir}}/init.sh"
    src: "{{conf_dir}}/init.sh.j2"
  when: install_type == "install"

- name: "start"
  shell: "bash {{work_dir}}/init.sh"
  when: install_type == "install"

- name: stop all {{service_name}}
  shell: "docker rm -f {{service_name}}"
  ignore_errors: true
  when: install_type == "delete"

- name: clean all {{service_name}} data
  shell: "rm -rf {{ work_dir }}"
  ignore_errors: true
  when: install_type == "delete"
