{
 "title": "用户自定义 HTTP 拨测",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Telegraf 配置TCP拨测", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "概览",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(net_response_result_code)",
     "legendFormat": "拨测总数"
    },
    {
     "expr": "count(net_response_result_code != 0) or vector(0)",
     "legendFormat": "拨测失败数"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    { "expr": "net_response_response_time", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "拨测失败详情",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "net_response_result_code != 0", "legendFormat": "auto" }
   ]
  },
  {
   "title": "Telegraf 配置 HTTP 拨测",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "概览",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(http_response_result_code)",
     "legendFormat": "拨测总数"
    },
    {
     "expr": "count(http_response_result_code != 0) or vector(0)",
     "legendFormat": "拨测失败数"
    }
   ]
  },
  {
   "title": "拨测失败",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(http_response_result_code != 0) or vector(0)",
     "legendFormat": "拨测失败数"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "http_response_response_time", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "拨测失败详情",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "http_response_result_code != 0", "legendFormat": "__auto" }
   ]
  }
 ]
}